apiVersion: apps/v1
kind: Deployment
metadata:
  name: krampoline
spec:
  selector:
    matchLabels:
      app: krampoline
  template:
    metadata:
      labels:
        app: krampoline
    spec:
      containers:
        - name: krampoline
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_fd34980ba039:latest
          env:
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: api-keys
                key: OPENAI_API_KEY
          - name: YOUTUBE_DATA_API_KEY
            valueFrom:
              secretKeyRef:
                name: api-keys
                key: YOUTUBE_DATA_API_KEY
