namespace: ask29961-namespace
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
secretGenerator:
- name: api-keys
  files:
  - OPENAI_API_KEY=api-keys/openai-key.txt
  - YOUTUBE_DATA_API_KEY=api-keys/youtube-key.txt