name: FastAPI CI Pipeline

on:
  push:
    branches: [ "build/TestBranch" ]
    paths-ignore:
      - 'src/rec_system/**'

jobs:
  quality-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install ruff pylint
    
#    # 코드 품질 체크
#    - name: Code Quality Check with Ruff
#      run: |
#        ruff check --select E,F,B,C4,PT,RUF src/
#        
#    - name: Code Quality Analysis with Pylint
#      run: |
#        pylint --disable=C0111,C0114,C0115,C0116,C0103,W0511,R0903,R0913,W0621,C0301,C0303,C0304,C0305,C0411,C0412,C0413,W0401,W0611,W0612,W0613,W0614,W0621,W0622,W0702,W0703,W0706 \
#        src/
        
    - name: Build Docker image
      run: |
        docker build -t joing-ai:latest .
        
    - name: Verify container starts
      run: |
        docker run -d --name joing-ai-test-container -p 8000:8000 joing-ai:latest
        # 컨테이너 실행 대기
        sleep 30

        # 컨테이너 상태 확인
        CONTAINER_STATUS=$(docker inspect joing-ai-test-container --format='{{.State.Status}}')
        if [ "$CONTAINER_STATUS" != "running" ]; then
          echo "Container failed to start. Status: $CONTAINER_STATUS"
          docker logs joing-ai-test-container
          exit 1
        fi
        
        # 헬스 체크
        HEALTH_CHECK=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/ready || echo "failed")
        if [ "$HEALTH_CHECK" != "200" ]; then
          echo "Health check failed. Status code: $HEALTH_CHECK"
          docker logs joing-ai-test-container
          exit 1
        fi
        
        echo "Container successfully started ..."

    # 빌드 결과 알림
    - name: Send Discord Notification - Success
      if: success()
      uses: sarisia/actions-status-discord@v1
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: "빌드 성공!!!"
        description: |
          **Branch**: ${{ github.ref_name }}
          **Build Number**: ${{ github.run_number }}
        color: 0x28A745 # Color Expression: 'GREEN'
        username: JOING CI BOT

    - name: Send Discord Notification - Failure
      if: failure()
      uses: sarisia/actions-status-discord@v1
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: "빌드 실패..."
        description: |
          **Branch**: ${{ github.ref_name }}
          **Build Number**: ${{ github.run_number }}
          **Action URL**: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        color: 0xDC3545 # Color Expression: 'RED'
        username: JOING CI BOT

    - name: Cleanup
      if: always()
      run: |
        docker stop joing-ai-test-container || true
        docker rm joing-ai-test-container || true
